### ISSUE TITLE
There are not enough examples

### ISSUE THREAD

**Issue by 0Nera** [paulloz/godot-action#55]
Please add an example of a project build using your extension

Thanks

**Comment by paulloz** [comment]
Hi, the action only takes care of giving you a usable installation of Godot. The way you use it in your workflows is heavily dependent on what you're trying to do and how your processes work 🤔  

You can see an example call in the run block in the README:
```yml
steps:
  ...
  - run: |
      godot --export <platform> <path-to-export-to>
```
But apart from that, how you can use the Godot CLI is described in the [official documentation](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html). How you decide to use it is really up to you.  

I can scrap some workflow files from my projects and paste them in this issue for reference but, as said before, they'll always rely a lot on how you've set your own CI processes and environments up...

**Comment by 0Nera** [comment]
TThank you very much, I accidentally missed the documentation
